#@ load("@ytt:data", "data")

#@ if/end data.values.privileged_clusterrole_name:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-privileged
  namespace: projectcontour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ data.values.privileged_clusterrole_name
subjects:
- kind: ServiceAccount
  name: envoy
  namespace: projectcontour
