#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ if/end data.values.cluster_type=="minikube":
#@overlay/match by=overlay.subset({"kind":"Service", "metadata": {"name": "envoy"}})
---
spec:
  type: ClusterIP
  #@overlay/match missing_ok=True
  #@overlay/remove
  externalTrafficPolicy:  
