#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#! TODO: Remove when 0.17.0 ships with imgpkgBundle support

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata" : { "name": "kapp-controller"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: kapp-controller
        image: alexbrand/kapp-controller@sha256:a67be43fc41fce6fcf015e10c70a403b8e61c7d5d4412ac825002c8a53dadf73