---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapps-cluster-admin
  namespace: kubeapps
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps-all-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeapps-cluster-admin
  namespace: kubeapps