---
# Source: kubeapps/templates/apprepositories.yaml
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: stable
  annotations:
    "helm.sh/hook": post-install
  labels:
    chart: kubeapps-3.7.2
    release: kubeapps
    heritage: Helm
    helm.sh/chart: kubeapps-3.7.2
    app.kubernetes.io/instance: kubeapps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeapps
    app: kubeapps-internal-apprepository-controller
spec:
  type: helm
  url: https://kubernetes-charts.storage.googleapis.com