#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #! INSERT HERE THE CONFIG