---
apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: registry-creds
spec:
  rules:
  - sourceSecret:
      name: registry-creds
      namespace: registry
    targetNamespaces:
      labelSelector:
        matchLabels:
          developer-namespace: "yes"
---
apiVersion: failk8s.dev/v1alpha1
kind: SecretInjectorConfig
metadata:
  name: registry-creds
spec:
  rules:
  - sourceSecrets:
      nameSelector:
        matchNames:
        - registry-creds
    serviceAccounts:
      nameSelector:
        matchNames:
        - default