#!/bin/bash

[ "$1" == "" ] && echo "You need to provide a module name to test" && exit 1

[ ! -d "$1" ] && echo "There's no module with that name" && exit 1

ytt -f values.yaml -f override.test.yml -f $1/upstream -f $1/config -f $1/downstream --ignore-unknown-comments