#@ load("@ytt:data", "data")
---
apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: eduk8s-wildcard
spec:
  rules:
  - sourceSecret:
      name: wildcard
      namespace: #@ data.values.ingress.namespace
    targetSecret:
      name: #@ data.values.eduk8s.wildcard
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ data.values.eduk8s.namespace

---
apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: eduk8s-registry-creds
spec:
  rules:
  - sourceSecret:
      name: registry-creds
      namespace: #@ data.values.registry.namespace
    targetSecret:
      name: eduk8s-registry-creds
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ data.values.eduk8s.namespace