#@ load("@ytt:data", "data")

---
apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: eduk8s-wildcard
spec:
  rules:
  - sourceSecret:
      name: wildcard
      namespace: #@ data.values.ingress.namespace
    targetSecret:
      name: #@ data.values.eduk8s.wildcard
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ data.values.eduk8s.namespace

---
apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: eduk8s-registry-creds
spec:
  rules:
  - sourceSecret:
      name: #@ "{}-creds".format(data.values.registry.name)
      namespace: #@ data.values.registry.namespace
    targetSecret:
      name: #@ "eduk8s-{}-creds".format(data.values.registry.name)
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ data.values.eduk8s.namespace

---
#! Docs: https://docs.eduk8s.io/en/latest/runtime-environment/system-profile.html
apiVersion: training.eduk8s.io/v1alpha1
kind: SystemProfile
metadata:
  name: default-system-profile
spec:
  ingress:
    domain: #@ data.values.wildcard_domain
    secret: #@ data.values.eduk8s.wildcard
    class: #@ data.values.ingress.type
  environment:
    secrets:
      pull:
      - #@ "eduk8s-{}-creds".format(data.values.registry.name)
  storage:
    #@ if/end data.values.privileged_clusterrole_name:
    group: 1
  theme:
    #@ if/end data.values.eduk8s.dashboard_style:
    dashboard:
      style: #@ data.values.eduk8s.dashboard_style
    #@ if/end data.values.eduk8s.workshop_style:
    workshop:
      style: #@ data.values.eduk8s.workshop_style
    #@ if/end data.values.eduk8s.portal_style:
    portal:
      style: #@ data.values.eduk8s.portal_style
  #@ if/end data.values.eduk8s.google_analytics:
  analytics:
    google:
      trackingId: #@ data.values.eduk8s.google_analytics
