#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ d = data.values.domain or assert.fail("missing domain definition")
#@ w = data.values.wildcard_domain or assert.fail("missing wildcard_domain definition")
#@ t = data.values.ingress.type or assert.fail("Ingress type needs to be specified")

#@ if data.values.cluster_type=="minikube":

#@overlay/match by=overlay.subset({"kind":"Service", "metadata": {"name": "envoy"}})
---
spec:
  type: ClusterIP
  #@overlay/match missing_ok=True
  #@overlay/remove
  externalTrafficPolicy:  
#@ end
