#@ load("@ytt:data", "data")
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretcopierconfigs.failk8s.dev
spec:
  scope: Cluster
  group: failk8s.dev
  names:
    plural: secretcopierconfigs
    singular: secretcopierconfig
    kind: SecretCopierConfig
    categories:
    - failk8s-operator
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    required:
                    - sourceSecret
                    properties:
                      sourceSecret:
                        type: object
                        required:
                        - name
                        - namespace
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                      targetNamespaces:
                        type: object
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          labelSelector:
                            type: object
                            required:
                            - matchLabels
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                      targetSecret:
                        type: object
                        properties:
                          name:
                            type: string
                          labels:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretinjectorconfigs.failk8s.dev
spec:
  scope: Cluster
  group: failk8s.dev
  names:
    plural: secretinjectorconfigs
    singular: secretinjectorconfig
    kind: SecretInjectorConfig
    categories:
    - failk8s-operator
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    required:
                    - sourceSecrets
                    properties:
                      targetNamespaces:
                        type: object
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          labelSelector:
                            type: object
                            required:
                            - matchLabels
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                      sourceSecrets:
                        type: object
                        oneOf:
                        - required:
                          - nameSelector
                        - required:
                          - labelSelector
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          labelSelector:
                            type: object
                            required:
                            - matchLabels
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                      serviceAccounts:
                        type: object
                        properties:
                          nameSelector:
                            type: object
                            required:
                            - matchNames
                            properties:
                              matchNames:
                                type: array
                                items:
                                  type: string
                          labelSelector:
                            type: object
                            required:
                            - matchLabels
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: failk8s-operator
  namespace: #@ data.values.registry.namespace
imagePullSecrets:
  - name: #@ "{}-creds".format(data.values.registry.name)

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: failk8s-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: failk8s-operator
  namespace: #@ data.values.registry.namespace
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: failk8s-operator
  namespace: #@ data.values.registry.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: failk8s-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: failk8s-operator
    spec:
      serviceAccountName: failk8s-operator
      containers:
      - name: operator
        image: quay.io/failk8s/failk8s-operator:latest
        imagePullPolicy: Always
      securityContext:
        runAsUser: 1
        runAsGroup: 1
