#@ load("@ytt:data", "data")

---
apiVersion: failk8s.dev/v1alpha1
kind: SecretCopierConfig
metadata:
  name: wildcard
spec:
  rules:
  - sourceSecret:
      name: wildcard
      namespace: #@ data.values.ingress.namespace
---