#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ServiceAccount", "metadata":{"name": "failk8s-operator"}})
---
#@overlay/match missing_ok=True
imagePullSecrets:
  - name: registry-creds