#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"TrainingPortal"}),expects="0+"
---
spec:
  #@overlay/match missing_ok=True
  portal:
    #@overlay/match missing_ok=True
    clients:
      robot:
        id: #@ data.values.eduk8s.robot.client_id
        secret: #@ data.values.eduk8s.robot.client_secret
    #@overlay/match missing_ok=True
    credentials:
      robot:
        username: #@ data.values.eduk8s.robot.username
        password: #@ data.values.eduk8s.robot.password