#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ registry_name = "registry.{}".format(data.values.domain)

#@ docker_auth = base64.encode("{}:{}".format(data.values.registry.admin.username, data.values.registry.admin.password))
#@ docker_creds = {"username": data.values.registry.admin.username, "password": data.values.registry.admin.password, "auth": docker_auth}

#@overlay/match by=overlay.subset({"kind":"Secret", "metadata": {"name": "registry-creds"}})
---
#! Secret for registry in operator install as namespace needs to exist
data:
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {registry_name: docker_creds}}))