#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ app = "oci-registry"

#@overlay/match by=overlay.subset({"kind": "Service"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  labels:
    #@overlay/match missing_ok=True
    app.kubernetes.io/part-of: #@ app

#@overlay/match by=overlay.subset({"kind": "Deployment"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  labels:
    #@overlay/match missing_ok=True
    app.kubernetes.io/part-of: #@ app
spec:
  template:
    metadata:
      labels:
        #@overlay/match missing_ok=True
        app.kubernetes.io/part-of: #@ app