#!/bin/bash

BASE="https://raw.githubusercontent.com/eduk8s/eduk8s/develop/resources"
declare -a CRDS=("training-portal.yaml" "workshop-environment.yaml" "workshop-request.yaml" "workshop-session.yaml" "workshop.yaml" "system-profile.yaml")
declare -a OPERATOR=("namespace.yaml" "rolebinding.yaml" "serviceaccount.yaml" "deployment.yaml")

CRDS_FILE="eduk8s-crds.yaml"
: > ${CRDS_FILE}
for val in "${CRDS[@]}"; do
  curl -skL ${BASE}/crds-v1/${val} >> ${CRDS_FILE}
  echo "---" >> ${CRDS_FILE}
done

OPERATOR_FILE="eduk8s-operator.yaml"
: > ${OPERATOR_FILE}
for val in "${OPERATOR[@]}"; do
  echo "curl -skL ${BASE}/operator/${val} >> ${OPERATOR_FILE}"
  curl -skL ${BASE}/operator/${val} >> ${OPERATOR_FILE}
  echo "---" >> ${OPERATOR_FILE}
done