apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-kubeapps-testing
spec:
  title: Kubeapps Testing
  description: Workshop environment for testing Kubeapps
  vendor: eduk8s.io
  difficulty: beginner
  duration: 60m
  url: https://github.com/eduk8s-tests/lab-kubeapps-testing
  content:
    files: github.com/eduk8s-tests/lab-kubeapps-testing
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
    dashboards:
    - name: Kubeapps
      url: $(ingress_protocol)://$(session_namespace)-kubeapps.$(ingress_domain)/
    ingresses:
    - name: kubeapps
      host: kubeapps.kubeapps.svc.cluster.local
      port: 0
    objects:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kubeapps-user
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: kubeapps-user
      rules:
      - apiGroups:
        - kubeapps.com
        resources:
        - apprepositories
        verbs:
        - create
        - delete
        - get
        - list
        - update
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kubeapps-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - kind: ServiceAccount
        namespace: $(session_namespace)
        name: kubeapps-user
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kubeapps-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: kubeapps-user
      subjects:
      - kind: ServiceAccount
        namespace: $(session_namespace)
        name: kubeapps-user
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: $(session_namespace)-kubeapps-user
        namespace: kubeapps
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: $(workshop_namespace)-kubeapps-user
      subjects:
      - kind: ServiceAccount
        namespace: $(session_namespace)
        name: kubeapps-user
  environment:
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: $(workshop_namespace)-kubeapps-user
        namespace: kubeapps
      rules:
      - apiGroups:
        - kubeapps.com
        resources:
        - apprepositories
        verbs:
        - get
        - list
