apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-spring-boot-k8s-probes
spec:
  vendor: eduk8s.io
  title: Adding Probes to Spring Boot on Kubernetes
  description: Add readiness and liveness probes to a Spring Boot application and deploy it to Kubernetes
  url: https://github.com/eduk8s-labs/lab-spring-boot-k8s-probes
  duration: 20m
  content: 
    image: jdk11-environment:*
    files: github.com/eduk8s-labs/lab-spring-boot-k8s-probes
  session:
    budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
    ingresses:
    - name: application
      port: 8080
    #dashboards:
    #- name: Application
    #  url: "$(ingress_protocol)://$(session_namespace)-application.$(ingress_domain)/"      
